import { cn } from "@/shared/ui/utils";
import { AppHeader } from "@/widgets/app-header/app-header";
import { Footer } from "@/widgets/footer";
import type { Metadata } from "next";
import localFont from "next/font/local";
import Image from "next/image";
import Script from "next/script";
import "./globals.css";

const Gerbera = localFont({
  src: [
    {
      path: "./fonts/Gerbera-Regular.woff",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/Gerbera-Medium.woff",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/Gerbera-Bold.woff",
      weight: "700",
      style: "normal",
    },
  ],
});

export const metadata: Metadata = {
  title: "Правда о ВИЧ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <head>
        <Script
          id="yandex-metrika"
          strategy="afterInteractive"
          dangerouslySetInnerHTML={{
            __html: `
              (function(m,e,t,r,i,k,a){m[i]=m[i]||function(){
              (m[i].a=m[i].a||[]).push(arguments)};
              m[i].l=1*new Date();
              k=e.createElement(t),a=e.getElementsByTagName(t)[0];
              k.async=1;k.src=r;a.parentNode.insertBefore(k,a)})
              (window, document, "script", "https://mc.yandex.ru/metrika/tag.js", "ym");

              ym(98985750, "init", {
                  clickmap:true,
                  trackLinks:true,
                  accurateTrackBounce:true,
                  webvisor:true
              });
            `,
          }}
        />
      </head>
      <body
        className={cn(
          "min-h-screen bg-background antialiased",
          Gerbera.className,
        )}
      >
        <AppHeader />
        {children}
        <Footer />

        <noscript>
          <div>
            <Image
              src="https://mc.yandex.ru/watch/98985750"
              className="absolute left-[-9999px]"
              alt=""
            />
          </div>
        </noscript>
      </body>
    </html>
  );
}
